DROP TABLE MEMBER;

DROP SEQUENCE SEQ_UNO;      -- 회원번호 발생시킬 시퀀스

--------------------------------------------------
----------------- MEMBER 관련 ---------------------	
--------------------------------------------------

CREATE TABLE MEMBER (
  USER_NO NUMBER PRIMARY KEY,               
  USER_ID VARCHAR2(30) NOT NULL UNIQUE,   
  USER_PWD VARCHAR2(100) NOT NULL,  
  USER_NAME VARCHAR2(15) NOT NULL,  
  PHONE VARCHAR2(13),              
  EMAIL VARCHAR2(100),            
  ADDRESS VARCHAR2(100),
  INTEREST VARCHAR2(100),
  ENROLL_DATE DATE DEFAULT SYSDATE,
  MODIFY_DATE DATE DEFAULT SYSDATE,
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.USER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.USER_ID IS '회원아이디';
COMMENT ON COLUMN MEMBER.USER_PWD IS '회원비밀번호';
COMMENT ON COLUMN MEMBER.USER_NAME IS '회원명';
COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';
COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';
COMMENT ON COLUMN MEMBER.ADDRESS IS '주소';
COMMENT ON COLUMN MEMBER.INTEREST IS '취미';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.MODIFY_DATE IS '정보수정일';
COMMENT ON COLUMN MEMBER.STATUS IS '상태값(Y/N)';

CREATE SEQUENCE SEQ_UNO
NOCACHE;

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'admin', '1234', '관리자', '010-1111-2222', 'admin@kh.or.kr', '서울시 강남구 역삼동', NULL, SYSDATE, SYSDATE, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user01', 'pass01', '홍길동', '010-3333-4444', 'user01@kh.or.kr', '서울시 양천구 목동', NULL, SYSDATE, SYSDATE, DEFAULT);

INSERT INTO MEMBER 
VALUES (SEQ_UNO.NEXTVAL, 'user02', 'pass02', '김말똥', '010-7444-1234', 'user02@kh.or.kr', '서울시 강서구', NULL, SYSDATE, SYSDATE, DEFAULT);


COMMIT;
